=== BWalusiak/uaim_lab/Laboratorium/ExaminationRooms/ExaminationRooms/Resources/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Database" type="DatabaseType"/>

    <xs:complexType name="DatabaseType">
        <xs:sequence>
            <xs:element name="ExaminationRooms" type="RoomsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="rooms" type="RoomsType"/>

    <xs:complexType name="RoomsType">
        <xs:sequence>
            <xs:element name="ExaminationRoom" type="RoomType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RoomType">
        <xs:sequence>
            <xs:element name="Number" type="xs:string"/>
            <xs:element name="Certifications" type="CertificationsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CertificationsType">
        <xs:sequence>
            <xs:element name="Certification" type="CertificationType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="CertificationType">
        <xs:sequence>
            <xs:element name="Type" type="xs:nonNegativeInteger"/>
            <xs:element name="GrantedAt" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== BWalusiak/uaim_lab/Laboratorium/ExaminationRooms/ExaminationRooms/Resources/database.xml
<?xml version="1.0" encoding="utf-8"?>
<Database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema.xsd">
    <ExaminationRooms>
        <ExaminationRoom>
            <Number>D123</Number>
            <Certifications>
                <Certification>
                    <Type>1</Type>
                    <GrantedAt>2002-09-24</GrantedAt>
                </Certification>
                <Certification>
                    <Type>5</Type>
                    <GrantedAt>2002-09-24</GrantedAt>
                </Certification>
            </Certifications>
        </ExaminationRoom>
        <ExaminationRoom>
            <Number>B154</Number>
            <Certifications>
                <Certification>
                    <Type>6</Type>
                    <GrantedAt>2002-09-24</GrantedAt>
                </Certification>
                <Certification>
                    <Type>2</Type>
                    <GrantedAt>2002-09-24</GrantedAt>
                </Certification>
                <Certification>
                    <Type>1</Type>
                    <GrantedAt>2002-09-24</GrantedAt>
                </Certification>
            </Certifications>
        </ExaminationRoom>
    </ExaminationRooms>
</Database>
