=== BWalusiak/uaim_lab/Laboratorium/ExaminationRooms/Resources/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="database" type="DatabaseType"/>

    <xs:complexType name="DatabaseType">
        <xs:sequence>
            <xs:element name="rooms" type="RoomsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="rooms" type="RoomsType"/>

    <xs:complexType name="RoomsType">
        <xs:sequence>
            <xs:element name="room" type="RoomType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RoomType">
        <xs:sequence>
            <xs:element name="number" type="xs:string"/>
            <xs:element name="certifications" type="CertificationsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CertificationsType">
        <xs:sequence>
            <xs:element name="certification" type="xs:nonNegativeInteger" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== BWalusiak/uaim_lab/Laboratorium/ExaminationRooms/Resources/database.xml
<?xml version="1.0" encoding="utf-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema.xsd">
    <rooms>
        <room>
            <number>D123</number>
            <certifications>
                <certification>5</certification>
                <certification>3</certification>
                <certification>2</certification>
                <certification>9</certification>
            </certifications>
        </room>
        <room>
            <number>A98</number>
            <certifications>
                <certification>0</certification>
                <certification>3</certification>
                <certification>5</certification>
                <certification>2</certification>
                <certification>7</certification>
                <certification>1</certification>
            </certifications>
        </room>
        <room>
            <number>B154</number>
            <certifications>
                <certification>5</certification>
                <certification>3</certification>
                <certification>1</certification>
            </certifications>
        </room>
    </rooms>
</database>
